version: "3.8"
services:
  certbot:
    image: certbot/certbot:v2.7.3
    command: "certonly --standalone --staple-ocsp --agree-tos -m jamielig@buffalo.edu -d chewker.com -d www.chewker.com"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/lib/letsencrypt 
      - ./data/certbot/logs:/var/log/letsencrypt
    ports:
      - "80:80"